# -*- coding: utf-8 -*-
"""Sentiment analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jgh1ney1s-D8lO4xliyDeC9ZTLgxb3wV
"""

!pip install transformers

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import torch
from torch.utils.data import Dataset,DataLoader
from transformers import BertTokenizer, BertForSequenceClassification
from torch.optim import AdamW
from transformers import get_scheduler

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")#check for gpu
print("Using device:", device)

df = pd.read_csv("twitter_training.csv.zip")

df.columns = ['id', 'entity', 'sentiment', 'text']

df.head()

tokenizer= BertTokenizer.from_pretrained("bert-base-uncased")

def preprocess_text(texts, tokenizer, max_length= 512):
    texts=[str(text) for text in texts]
    encoding=tokenizer(
      texts,
      padding=True,
      truncation=True,
      max_length=max_length,
      return_tensors="pt",
      return_attention_mask=True
    )
    return encoding

# Preprocess text data in the dataset
texts = df['text'].tolist()  # Convert the text column to a list
encoding = preprocess_text(texts, tokenizer)

class SentimentDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: val[idx] for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

df.head()

print(df['sentiment'].unique())

# Step 1: Clean the sentiment column properly
df['sentiment'] = df['sentiment'].str.strip()         # remove leading/trailing spaces
df['sentiment'] = df['sentiment'].str.capitalize()    # make 'positive' -> 'Positive'

# Step 2: Remove unwanted labels (Irrelevant)
df = df[df['sentiment'].isin(['Positive', 'Negative', 'Neutral'])]

# Step 3: Now map
sentiment_mapping = {'Positive': 0, 'Negative': 1, 'Neutral': 2}
df['sentiment'] = df['sentiment'].map(sentiment_mapping)

# Step 4: Check
print(df.head())

train_texts, val_texts, train_labels, val_labels = train_test_split(
    df['text'].tolist(),
    df['sentiment'].tolist(),
    test_size=0.2,
    random_state=42
)

train_texts = [str(text) for text in train_texts]
val_texts = [str(text) for text in val_texts]

train_encodings = tokenizer(train_texts, truncation=True, padding=True, max_length=512, return_tensors='pt')
val_encodings = tokenizer(val_texts, truncation=True, padding=True, max_length=512, return_tensors='pt')

# Create dataset objects
train_dataset = SentimentDataset(train_encodings, train_labels)
val_dataset = SentimentDataset(val_encodings, val_labels)


train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=16)

model =BertForSequenceClassification.from_pretrained('bert-base-uncased',num_labels=3)
model.to(device)

optimizer=AdamW(model.parameters(), lr=2e-5)

# Learning rate scheduler (linear warmup)
num_epochs = 3
num_training_steps = num_epochs * len(train_loader)
lr_scheduler = get_scheduler(
    "linear",
    optimizer=optimizer,
    num_warmup_steps=0,
    num_training_steps=num_training_steps
)

import torch
from torch import nn
from tqdm import tqdm

# Define your loss function

# Example: Class weights based on your dataset distribution
# For example, class weights for [Negative, Neutral, Positive]
class_weights = torch.tensor([1.0, 1.0, 2.0]).to(device)  # Adjust weights as needed
loss_fn = nn.CrossEntropyLoss(weight=class_weights)

# Initialize the BERT model
model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=3)
model.to(device)

# Define the optimizer
optimizer = AdamW(model.parameters(), lr=2e-5)

# Training loop with the updated loss function
num_epochs = 3
for epoch in range(num_epochs):
    model.train()
    total_loss = 0
    for batch in tqdm(train_loader, desc=f"Epoch {epoch+1}/{num_epochs}"):
        batch = {k: v.to(device) for k, v in batch.items()}
        labels = batch['labels']

        optimizer.zero_grad()

        outputs = model(**batch)
        logits = outputs.logits

        # Compute loss with class weights
        loss = loss_fn(logits, labels)
        total_loss += loss.item()

        # Backward pass and optimizer step
        loss.backward()
        optimizer.step()

    avg_loss = total_loss / len(train_loader)
    print(f"Epoch {epoch+1} Loss: {avg_loss:.4f}")

from sklearn.metrics import classification_report
import torch

# Evaluate the model and generate classification report
all_preds = []
all_labels = []

model.eval()
with torch.no_grad():
    for batch in val_loader:
        batch = {k: v.to(device) for k, v in batch.items()}
        labels = batch['labels']
        outputs = model(**batch)
        preds = torch.argmax(outputs.logits, dim=-1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

# Classification report
print(classification_report(all_labels, all_preds, target_names=['Negative', 'Neutral', 'Positive']))

# Save the model
model.save_pretrained('sentiment_bert_model')
tokenizer.save_pretrained('sentiment_bert_tokenizer')

from sklearn.metrics import classification_report

# Collect all true labels and predictions
all_preds = []
all_labels = []

model.eval()
with torch.no_grad():
    for batch in val_loader:
        batch = {k: v.to(device) for k, v in batch.items()}
        labels = batch['labels']
        outputs = model(**batch)
        preds = torch.argmax(outputs.logits, dim=-1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

# Classification report
print(classification_report(all_labels, all_preds, target_names=['Negative', 'Neutral', 'Positive']))

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(all_labels, all_preds)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Negative', 'Neutral', 'Positive'], yticklabels=['Negative', 'Neutral', 'Positive'])
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()

model = BertForSequenceClassification.from_pretrained('sentiment_bert_model')
tokenizer = BertTokenizer.from_pretrained('sentiment_bert_tokenizer')
model.to(device)
model.eval()

def predict_sentiment(text):
    inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True)
    inputs = {k: v.to(device) for k, v in inputs.items()}
    with torch.no_grad():
        outputs = model(**inputs)
        logits = outputs.logits
    print(f"Logits: {logits}")
    prediction = torch.argmax(logits, dim=-1)
    sentiment = ['Negative', 'Neutral', 'Positive'][prediction]
    return sentiment

# Test
print(predict_sentiment("I love this product! It's amazing."))
print(predict_sentiment("This is so bad. I'm very disappointed."))